server:
  port: 8113

spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: http://192.168.204.129:8848      #??????
      discovery:
        namespace: wangtao
        cluster-name: SZ
    gateway:
      #      default-filters: # ??????????????????
      #        - AddRequestHeader=Truth, Itcast is freaking awesome! # ?????
      routes: #??????
        - id: user-service     #??Id.??????????
          #uri: http://127.0.0.1:8111      # ??????? http??????
          uri: lb://userservice             #??????
          predicates: #???????????????????
            - Path=/user/**                  #?????????????user??
          filters: #???????????
            - AddRequestHeader=Truth, Itcast is freaking awesome! # ?????
        - id: order-service
          uri: lb://orderservice
          predicates:
            - Path=/order/**

