server:
  port: 8111
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/study?useSSL=false
    username: root
    password: wt2109
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  file:
    name: log/log.log
  level:
    root: info
    cn.itcast: debug
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8112/eureka   #eureka单机地址或者集群地址

