server:
  port: 8110
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/study?useSSL=false
    username: root
    password: wt2109
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: orderserver    #order 服务注册到注册中心的名字
  cloud:
    nacos:
      server-addr: http://192.168.204.129:8848
      discovery:
        cluster-name: SZ  #配置集群名称，也就是机房位置（服务分级），服务请求优先调用本地服务，本地服务不存在可以调用集群其他服务
        namespace: wangtao   #环境隔离，不同环境下的服务不能相互调用(管理后台配置)

mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  file:
    name: log/log.log
  level:
    root: info
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8112/eureka

ribbon:
  eager-load: ## ribbon 饿加载机制
    enabled: true
    clients: userserver   # # 针对某个服务的饿加载
