server:
  port: 8112

spring:
  application:
    name: eurekaserver      #eurekaf??????????????????????eureka??????????

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8112/eureka   #eureka??????????